name: Bundle API Release

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: Forsakringskassan/.github/.github/workflows/bundle-api-npm-release.yaml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}